# Generated by Django 3.1.2 on 2020-11-06 15:40

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مقاله')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوای مقاله')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 10, 26, 883121), verbose_name='زمان ارسال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مدیریت مقالات',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_title', models.CharField(max_length=100, verbose_name='عنوان دسته')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان انگلیسی دسته')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='عنوان در آدرس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'مدیریت دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_title', models.CharField(max_length=100, verbose_name='عنوان تگ')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان انگلیسی تگ')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='عنوان در آدرس')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'مدیریت تگ ها',
            },
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'نظری ندارم'), (1, 'می پسندم'), (2, 'نمی پسندم')], default=0, verbose_name='رای')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_blog.blog', verbose_name='بلاگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ویوی بلاگ',
                'verbose_name_plural': 'مدیریت ویو بلاگ ها',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='shop_blog.BlogCategory', verbose_name='مربوط به دسته بندی های'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='shop_blog.BlogTag', verbose_name='مربوط به تگ های'),
        ),
    ]
