# Generated by Django 3.1.2 on 2020-11-06 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 11, 34, 937702), verbose_name='زمان ارسال'),
        ),
    ]
