# Generated by Django 3.1.2 on 2020-11-06 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0002_auto_20201106_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 19, 15, 35, 943266), verbose_name='زمان ارسال'),
        ),
    ]
