# Generated by Django 3.1.2 on 2020-11-06 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0005_auto_20201106_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogview',
            name='vote',
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 21, 10, 10, 57711), verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='user',
            field=models.CharField(max_length=15, verbose_name='آی پی بازدید کننده'),
        ),
    ]
