# Generated by Django 3.1.2 on 2020-11-09 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0011_auto_20201109_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 21, 0, 51, 229005), verbose_name='زمان ارسال'),
        ),
    ]
