# Generated by Django 3.1.2 on 2020-11-09 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0015_auto_20201109_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 1, 57, 9, 422873), verbose_name='زمان ارسال'),
        ),
    ]
