# Generated by Django 3.1.2 on 2020-11-12 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0016_auto_20201110_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 15, 19, 21, 704065), verbose_name='زمان ارسال'),
        ),
    ]
