# Generated by Django 3.1.2 on 2020-11-12 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0021_auto_20201112_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 20, 56, 16, 951567), verbose_name='زمان ارسال'),
        ),
    ]
