# Generated by Django 3.1.2 on 2020-11-12 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0024_auto_20201113_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 2, 19, 26, 752427), verbose_name='زمان ارسال'),
        ),
    ]
