# Generated by Django 3.1.2 on 2020-11-13 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0030_auto_20201113_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 18, 6, 17, 928399), verbose_name='زمان ارسال'),
        ),
    ]
