# Generated by Django 3.1.2 on 2020-11-13 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_blog', '0033_auto_20201113_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 20, 2, 27, 739892), verbose_name='زمان ارسال'),
        ),
    ]
