# Generated by Django 3.1.2 on 2020-11-12 22:43

from django.db import migrations, models
import django_resized.forms
import tinakala.utils.upload_file_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان بنر')),
                ('position', models.IntegerField(choices=[(1, 'کنار اسلایدر اصلی سایت'), (2, 'پایین پرفروش ترین ها')], default=1, verbose_name='محل قرار گیری بنر')),
                ('image', models.ImageField(upload_to=tinakala.utils.upload_file_manager.upload_home_page_banners, verbose_name='رسانه بنر')),
                ('url', models.CharField(max_length=120, verbose_name='لینک صفحه بنر')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'مدیریت بنر صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اسلاید')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=150, size=[873, 437], upload_to=tinakala.utils.upload_file_manager.upload_home_page_slider, verbose_name='تصویر اسلاید')),
                ('url', models.CharField(max_length=120, verbose_name='مربوط به صفحه')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'مدیریت اسلایدر صفحه اصلی',
            },
        ),
    ]
