# Generated by Django 3.1.2 on 2020-11-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='آی پی کاربر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
