# Generated by Django 3.1.2 on 2020-11-13 10:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0002_newsletters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletters',
            options={'verbose_name': 'خبرنامه', 'verbose_name_plural': 'مدیریت خبرنامه'},
        ),
        migrations.CreateModel(
            name='NewslettersMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان خبر')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن خبرنامه')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان خبر')),
                ('to_users', models.ManyToManyField(blank=True, to='shop_website.Newsletters', verbose_name='ارسال به کاربران')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'مدیریت خبرنامه',
            },
        ),
    ]
