# Generated by Django 3.1.2 on 2020-11-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0004_auto_20201113_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersmessage',
            name='message',
            field=models.TextField(verbose_name='متن خبرنامه'),
        ),
    ]
