# Generated by Django 3.1.2 on 2020-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0005_auto_20201113_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersmessage',
            name='html',
            field=models.TextField(blank=True, null=True, verbose_name='محتوای html'),
        ),
    ]
