# Generated by Django 3.1.2 on 2020-10-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان دسته')),
                ('depth', models.IntegerField(choices=[(1, 'دسته بندی سطح 1'), (2, 'دسته بندی سطح 2'), (3, 'دسته بندی سطح 3')], default=1, verbose_name='دسته مربوط به سطح')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'مدیریت دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_categories.category', verbose_name='دسته والد')),
                ('sub_category', models.ManyToManyField(related_name='sub_category', to='shop_categories.Category', verbose_name='دسته فرزند')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان خصوصیت دسته')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_categories.category', verbose_name='مربوط به دسته')),
            ],
            options={
                'verbose_name': 'گروه خصوصیت',
                'verbose_name_plural': 'مدیریت گروه خصوصیت',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان خصوصیت')),
                ('attr_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_categories.attributegroup', verbose_name='مربوط به دسته خصوصیت')),
            ],
            options={
                'verbose_name': 'خصوصیت',
                'verbose_name_plural': 'مدیریت خصوصیت',
            },
        ),
    ]
