# Generated by Django 3.1.2 on 2020-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoryparent',
            options={'verbose_name': 'زیر دسته', 'verbose_name_plural': 'مدیریت ارث بری دسته بندی'},
        ),
        migrations.AddField(
            model_name='category',
            name='en_title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='عنوان انگلیسی دسته'),
        ),
    ]
