# Generated by Django 3.1.2 on 2020-10-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0003_auto_20201022_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategoryparent',
            old_name='main_category',
            new_name='category',
        ),
    ]
