# Generated by Django 3.1.2 on 2020-10-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0004_auto_20201022_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryparent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop_categories.category', verbose_name='دسته والد'),
        ),
        migrations.RemoveField(
            model_name='subcategoryparent',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategoryparent',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='shop_categories.category', verbose_name='دسته فرزند'),
            preserve_default=False,
        ),
    ]
