# Generated by Django 3.1.2 on 2020-10-22 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0005_auto_20201022_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryparent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_categories.category', verbose_name='دسته والد'),
        ),
        migrations.RemoveField(
            model_name='subcategoryparent',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategoryparent',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_category', to='shop_categories.Category', verbose_name='دسته فرزند'),
        ),
    ]
