# Generated by Django 3.1.2 on 2020-10-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0006_auto_20201022_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryparent',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_category', to='shop_categories.Category', verbose_name='دسته فرزند'),
        ),
    ]
