# Generated by Django 3.1.2 on 2020-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0008_auto_20201027_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان برند')),
                ('categories', models.ManyToManyField(to='shop_categories.Category', verbose_name='مربوط به دسته های')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'مدیریت برندها',
            },
        ),
    ]
