# Generated by Django 3.1.2 on 2020-11-12 22:43

from django.db import migrations
import django_resized.forms
import tinakala.utils.upload_file_manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0010_brands_en_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoryparent',
            options={'verbose_name': 'زیر دسته', 'verbose_name_plural': 'مدیریت ارث بری دسته'},
        ),
        migrations.AddField(
            model_name='brands',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=150, size=[205, 205], upload_to=tinakala.utils.upload_file_manager.upload_brand_logo, verbose_name='لوگوی برند'),
        ),
    ]
