# Generated by Django 3.1.2 on 2020-10-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinakala.utils.upload_file_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[128, 128], upload_to=tinakala.utils.upload_file_manager.upload_user_avatar, verbose_name='آواتار کاربر')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه')),
                ('phone_verify', models.BooleanField(default=0, verbose_name='تایید شماره همراه')),
                ('otp', models.CharField(blank=True, max_length=5, null=True, verbose_name='کد تایید موبایل')),
                ('otp_generated_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ otp')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'مرد'), (2, 'زن')], default=1, null=True, verbose_name='جنسیت')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('done', models.BooleanField(default=0, verbose_name='تکمیل پروفایل')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='امتیاز کاربر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('address', models.TextField(max_length=500, verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('plaque', models.CharField(max_length=10, verbose_name='پلاک منزل')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_settings.city', verbose_name='شهر')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_settings.state', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='برای حساب کاربری')),
            ],
            options={
                'verbose_name': 'آدرس های کاربر',
                'verbose_name_plural': 'آدرس های کاربران',
            },
        ),
    ]
