# Generated by Django 3.1.2 on 2020-10-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0021_auto_20201026_0134'),
        ('shop_accounts', '0003_auto_20201026_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='shop_products.Product', verbose_name='محصولات مورد علاقه'),
        ),
    ]
