# Generated by Django 3.1.2 on 2020-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0022_auto_20201027_1638'),
        ('shop_accounts', '0004_auto_20201026_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='product',
            field=models.ManyToManyField(blank=True, to='shop_products.Product', verbose_name='محصولات مورد علاقه'),
        ),
    ]
