# Generated by Django 3.1.2 on 2020-11-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_accounts', '0007_useraddress_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_accounts.userprofile', verbose_name='برای پروفایل'),
        ),
    ]
