# Generated by Django 3.1.2 on 2020-11-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_accounts', '0008_useraddress_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='profile',
        ),
    ]
