# Generated by Django 3.1.2 on 2020-10-21 21:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن تیکت')),
                ('created_at', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده/نشده')),
                ('answered', models.BooleanField(default=False, verbose_name='پاسخ داده شده/نشده')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='پاسخ تیکت')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'مدیریت تیکت ها',
            },
        ),
    ]
