# Generated by Django 3.1.2 on 2020-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0002_auto_20201022_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(verbose_name='متن پیام'),
        ),
    ]
