# Generated by Django 3.1.2 on 2020-11-03 18:29

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_contact', '0003_auto_20201103_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تیکت')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن تیکت')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تیکت مربوط به کاربر')),
            ],
            options={
                'verbose_name': 'تیک کاربر',
                'verbose_name_plural': 'مدیریت تیکت کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserTicketAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='پاسخ تیکت')),
                ('timestamp', models.DateTimeField(verbose_name='زمان پاسخ تیکت')),
                ('read', models.BooleanField(verbose_name='خوانده شده/نشده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_contact.userticket', verbose_name='مربوط به تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر پاسخ دهنده')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'مدیریت پاسخ تیکت ها',
            },
        ),
    ]
