# Generated by Django 3.1.2 on 2020-11-04 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0007_auto_20201104_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 0, 20, 3, 434707), verbose_name='زمان ایجاد تیکت'),
        ),
        migrations.AlterField(
            model_name='userticketanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 0, 20, 3, 434707), verbose_name='زمان پاسخ تیکت'),
        ),
    ]
