# Generated by Django 3.1.2 on 2020-11-06 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0008_auto_20201105_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 21, 10, 10, 52726), verbose_name='زمان ایجاد تیکت'),
        ),
        migrations.AlterField(
            model_name='userticketanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 21, 10, 10, 52726), verbose_name='زمان پاسخ تیکت'),
        ),
    ]
