# Generated by Django 3.1.2 on 2020-11-09 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0015_auto_20201109_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 21, 22, 47, 447133), verbose_name='زمان ایجاد تیکت'),
        ),
        migrations.AlterField(
            model_name='userticketanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 21, 22, 47, 448131), verbose_name='زمان پاسخ تیکت'),
        ),
    ]
