# Generated by Django 3.1.2 on 2020-11-12 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0022_auto_20201112_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 20, 43, 23, 904641), verbose_name='زمان ایجاد تیکت'),
        ),
        migrations.AlterField(
            model_name='userticketanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 20, 43, 23, 905638), verbose_name='زمان پاسخ تیکت'),
        ),
    ]
