# Generated by Django 3.1.2 on 2020-11-12 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0025_auto_20201112_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 2, 13, 0, 892800), verbose_name='زمان ایجاد تیکت'),
        ),
        migrations.AlterField(
            model_name='userticketanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 2, 13, 0, 897910), verbose_name='زمان پاسخ تیکت'),
        ),
    ]
