# Generated by Django 3.1.2 on 2020-11-12 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_contact', '0028_auto_20201113_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 2, 23, 47, 20265), verbose_name='زمان ایجاد تیکت'),
        ),
        migrations.AlterField(
            model_name='userticketanswer',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 2, 23, 47, 20265), verbose_name='زمان پاسخ تیکت'),
        ),
    ]
