# Generated by Django 3.1.2 on 2020-10-23 13:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tinakala.utils.upload_file_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_categories', '0007_auto_20201023_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('fa_title', models.CharField(max_length=120, verbose_name='عنوان محصول به فارسی')),
                ('en_title', models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان محصول به انگلیسی')),
                ('code', models.CharField(max_length=12, verbose_name='کد محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('review', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن نقد و بررسی')),
                ('avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=150, size=[350, 350], upload_to=tinakala.utils.upload_file_manager.upload_product_avatar, verbose_name='عکس محصول')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/ غیر فعال')),
                ('root_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_categories.category', verbose_name='مربوط به دسته')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_categories.category', verbose_name='مربوط به دسته')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار خصوصیت')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_categories.attribute', verbose_name='خصوصیت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product', verbose_name='مربوط به محصول')),
            ],
        ),
    ]
