# Generated by Django 3.1.2 on 2020-10-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0007_auto_20201023_1624'),
        ('shop_products', '0002_auto_20201023_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='root_category',
        ),
        migrations.RemoveField(
            model_name='productcategories',
            name='category',
        ),
        migrations.AddField(
            model_name='productcategories',
            name='category',
            field=models.ManyToManyField(to='shop_categories.Category', verbose_name='مربوط به دسته'),
        ),
    ]
