# Generated by Django 3.1.2 on 2020-10-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0007_auto_20201023_1624'),
        ('shop_products', '0003_auto_20201023_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'مدیریت محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop_categories.Category', verbose_name='مربوط به دسته'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='عنوان در آدرس'),
        ),
        migrations.DeleteModel(
            name='ProductCategories',
        ),
    ]
