# Generated by Django 3.1.2 on 2020-10-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0004_auto_20201024_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'خصوصیت محصول', 'verbose_name_plural': 'مدیریت خصوصیات محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد محصول'),
        ),
    ]
