# Generated by Django 3.1.2 on 2020-10-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0005_auto_20201024_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fa_title',
            new_name='title',
        ),
    ]
