# Generated by Django 3.1.2 on 2020-10-25 11:11

from django.db import migrations, models
import django.db.models.deletion
import tinakala.utils.upload_file_manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0008_auto_20201024_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to=tinakala.utils.upload_file_manager.upload_product_media, verbose_name='رسانه مربوط به محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product', verbose_name='مربوط به محصول')),
            ],
            options={
                'verbose_name': 'رسانه های محصول',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
    ]
