# Generated by Django 3.1.2 on 2020-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0009_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='type',
            field=models.IntegerField(choices=[(1, 'عکس (png, jpg, ...)'), (2, 'ویدیو (mp4, ...)')], default=1, verbose_name='نوع رسانه'),
            preserve_default=False,
        ),
    ]
