# Generated by Django 3.1.2 on 2020-10-25 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_products', '0011_auto_20201025_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=600, verbose_name='متن پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('verified', models.BooleanField(default=False, verbose_name='تایید شده/نشده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product', verbose_name='مربوط به محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='متعلق به کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'مدیریت نظرات محصولات',
            },
        ),
    ]
