# Generated by Django 3.1.2 on 2020-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0012_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(verbose_name='زمان ارسال'),
        ),
    ]
