# Generated by Django 3.1.2 on 2020-10-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0013_auto_20201025_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='function',
            field=models.IntegerField(choices=[(1, 'بسیار کم'), (2, 'کم'), (3, 'متوسط'), (4, 'زیاد'), (5, 'بسیار زیاد')], default=3, verbose_name='عملکرد'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='quality',
            field=models.IntegerField(choices=[(1, 'بسیار کم'), (2, 'کم'), (3, 'متوسط'), (4, 'زیاد'), (5, 'بسیار زیاد')], default=3, verbose_name='کیفیت ساخت'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='worth',
            field=models.IntegerField(choices=[(1, 'بسیار کم'), (2, 'کم'), (3, 'متوسط'), (4, 'زیاد'), (5, 'بسیار زیاد')], default=3, verbose_name='ارزش خرید'),
        ),
    ]
