# Generated by Django 3.1.2 on 2020-10-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0014_auto_20201025_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='advised',
            field=models.BooleanField(choices=[(True, 'خرید این محصول را توصیه می کنم'), (False, 'خرید این محصول را توصیه نمی کنم')], default=True, verbose_name='توصیه به خرید میشود/نمی شود'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(max_length=600, verbose_name='متن نظر'),
        ),
    ]
