# Generated by Django 3.1.2 on 2020-10-25 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0015_auto_20201025_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 21, 54, 42, 859424), verbose_name='زمان ارسال'),
        ),
    ]
