# Generated by Django 3.1.2 on 2020-10-25 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0016_auto_20201025_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='عنوان نظر'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 22, 55, 18, 510047), verbose_name='زمان ارسال'),
        ),
    ]
