# Generated by Django 3.1.2 on 2020-10-25 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0018_auto_20201025_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='advised',
            field=models.BooleanField(choices=[(True, 'این محصول را توصیه می کنم'), (False, 'این محصول را توصیه نمی کنم')], default=True, verbose_name='توصیه به خرید میشود/نمی شود'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 1, 32, 21, 108285), verbose_name='زمان ارسال'),
        ),
    ]
