# Generated by Django 3.1.2 on 2020-10-25 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0019_auto_20201026_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 1, 33, 46, 171740), verbose_name='زمان ارسال'),
        ),
    ]
