# Generated by Django 3.1.2 on 2020-10-25 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0020_auto_20201026_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 26, 1, 34, 59, 262097), verbose_name='زمان ارسال'),
        ),
    ]
