# Generated by Django 3.1.2 on 2020-10-27 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0021_auto_20201026_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 16, 38, 44, 854338), verbose_name='زمان ارسال'),
        ),
    ]
