# Generated by Django 3.1.2 on 2020-10-27 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0022_auto_20201027_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='promote',
            field=models.BooleanField(default=True, verbose_name='تایید توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 20, 9, 18, 160967), verbose_name='زمان ارسال'),
        ),
    ]
