# Generated by Django 3.1.2 on 2020-10-27 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0023_auto_20201027_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 21, 8, 31, 618775), verbose_name='زمان ارسال'),
        ),
    ]
