# Generated by Django 3.1.2 on 2020-10-30 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0024_auto_20201027_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 22, 55, 8, 424763), verbose_name='زمان ارسال'),
        ),
    ]
