# Generated by Django 3.1.2 on 2020-10-30 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0025_auto_20201030_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 22, 57, 4, 859992), verbose_name='زمان ارسال'),
        ),
    ]
