# Generated by Django 3.1.2 on 2020-10-30 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_categories', '0010_brands_en_title'),
        ('shop_products', '0026_auto_20201030_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_categories.brands', verbose_name='برند کالا'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 23, 4, 7, 160493), verbose_name='زمان ارسال'),
        ),
    ]
