# Generated by Django 3.1.2 on 2020-11-03 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0027_auto_20201030_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 21, 8, 38, 371779), verbose_name='زمان ارسال'),
        ),
    ]
