# Generated by Django 3.1.2 on 2020-11-04 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0028_auto_20201103_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 23, 2, 47, 998125), verbose_name='زمان ارسال'),
        ),
    ]
