# Generated by Django 3.1.2 on 2020-11-04 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0029_auto_20201104_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 23, 12, 33, 300256), verbose_name='زمان ارسال'),
        ),
    ]
