# Generated by Django 3.1.2 on 2020-11-04 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0030_auto_20201104_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 0, 20, 3, 434707), verbose_name='زمان ارسال'),
        ),
    ]
