# Generated by Django 3.1.2 on 2020-11-08 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0032_auto_20201106_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 18, 28, 15, 119689), verbose_name='زمان ارسال'),
        ),
    ]
