# Generated by Django 3.1.2 on 2020-11-09 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0034_auto_20201109_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0, verbose_name='موجودی کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'اتمام موجودی کالا'), (1, 'موجودی فعال برای کالا')], default=0, verbose_name='وضعیت موجودی کالا'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 12, 55, 45, 760028), verbose_name='زمان ارسال'),
        ),
    ]
