# Generated by Django 3.1.2 on 2020-11-09 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0035_auto_20201109_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(False, 'اتمام موجودی کالا'), (True, 'موجودی فعال برای کالا')], default=0, verbose_name='وضعیت موجودی کالا'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 13, 56, 25, 248341), verbose_name='زمان ارسال'),
        ),
    ]
