# Generated by Django 3.1.2 on 2020-11-09 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0036_auto_20201109_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 20, 23, 2, 503593), verbose_name='زمان ارسال'),
        ),
    ]
