# Generated by Django 3.1.2 on 2020-11-09 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0041_auto_20201109_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 21, 23, 17, 183125), verbose_name='زمان ارسال'),
        ),
    ]
