# Generated by Django 3.1.2 on 2020-11-10 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0045_auto_20201111_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvisit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 0, 30, 24, 448181), verbose_name='زمان بازدید'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 0, 30, 24, 448181), verbose_name='زمان ارسال'),
        ),
    ]
