# Generated by Django 3.1.2 on 2020-11-10 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0046_auto_20201111_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 0, 31, 54, 429068), verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بازدید'),
        ),
    ]
