# Generated by Django 3.1.2 on 2020-11-10 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0048_auto_20201111_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='فروش کل محصول'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 1, 22, 22, 886529), verbose_name='زمان ارسال'),
        ),
    ]
