# Generated by Django 3.1.2 on 2020-11-11 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0049_auto_20201111_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی کالا'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 14, 54, 47, 985169), verbose_name='زمان ارسال'),
        ),
    ]
