# Generated by Django 3.1.2 on 2020-11-12 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0051_auto_20201112_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 15, 50, 54, 834186), verbose_name='زمان ارسال'),
        ),
    ]
