# Generated by Django 3.1.2 on 2020-11-12 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0052_auto_20201112_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 13, 50, 347761), verbose_name='زمان ارسال'),
        ),
    ]
