# Generated by Django 3.1.2 on 2020-11-12 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0053_auto_20201112_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 20, 43, 23, 887686), verbose_name='زمان ارسال'),
        ),
    ]
