# Generated by Django 3.1.2 on 2020-11-12 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0056_auto_20201112_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 2, 13, 0, 887791), verbose_name='زمان ارسال'),
        ),
    ]
