# Generated by Django 3.1.2 on 2020-11-12 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0057_auto_20201113_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 2, 18, 15, 107097), verbose_name='زمان ارسال'),
        ),
    ]
