# Generated by Django 3.1.2 on 2020-11-13 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0060_auto_20201113_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 10, 25, 1, 716988), verbose_name='زمان ارسال'),
        ),
    ]
