# Generated by Django 3.1.2 on 2020-11-13 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0063_auto_20201113_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 16, 11, 3, 26538), verbose_name='زمان ارسال'),
        ),
    ]
