# Generated by Django 3.1.2 on 2020-11-13 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0064_auto_20201113_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 18, 6, 17, 917428), verbose_name='زمان ارسال'),
        ),
        migrations.CreateModel(
            name='ProductAmazing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول شگفت انگیز',
                'verbose_name_plural': 'مدیریت محصولات شگفت انگیز',
            },
        ),
    ]
