# Generated by Django 3.1.2 on 2020-11-13 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0065_auto_20201113_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productamazing',
            old_name='percent',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 18, 31, 42, 61436), verbose_name='زمان ارسال'),
        ),
    ]
