# Generated by Django 3.1.2 on 2020-11-13 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0069_auto_20201113_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 20, 29, 20, 363859), verbose_name='زمان ارسال'),
        ),
    ]
