# Generated by Django 3.1.2 on 2020-11-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_products', '0033_auto_20201108_1828'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('authority', models.CharField(max_length=200, verbose_name='کد اعتبار')),
            ],
            options={
                'verbose_name': 'صورتحساب',
                'verbose_name_plural': 'مدیریت صورتحساب ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مربوط به کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'مدیریت سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'در انتظار بررسی'), (0, 'سفارش لغو شده'), (2, 'سفارش کامل شده')], default=1)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_order.invoice', verbose_name='مربوط به صورت حساب')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'مدیریت تراکنش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveBigIntegerField(verbose_name='قیمت محصول')),
                ('product_count', models.IntegerField(verbose_name='تعداد محصول')),
                ('product_cost', models.PositiveBigIntegerField(verbose_name='هزینه کل محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_order.order', verbose_name='مربوط به سبد خرید')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول در سبد',
                'verbose_name_plural': 'مدیریت محصولات در سبد',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_order.order', verbose_name='مربوط به سبد'),
        ),
    ]
