# Generated by Django 3.1.2 on 2020-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.BooleanField(choices=[(False, 'پرداخت نشده'), (True, 'پرداخت شده')], default=False, verbose_name='پرداخت شده/نشده'),
        ),
    ]
