# Generated by Django 3.1.2 on 2020-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0003_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, 'باطل شده'), (1, 'پرداخت نشده'), (2, 'پرداخت شده')], default=0, verbose_name='پرداخت شده/نشده'),
        ),
    ]
