# Generated by Django 3.1.2 on 2020-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0004_auto_20201109_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(0, 'باطل شده'), (1, 'پرداخت نشده'), (2, 'پرداخت شده')], default=1, verbose_name='پرداخت شده/نشده'),
        ),
    ]
