# Generated by Django 3.1.2 on 2020-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0005_auto_20201109_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(False, 'پرداخت نشده'), (True, 'پرداخت شده')], default=False, verbose_name='پرداخت شده/نشده'),
        ),
    ]
