# Generated by Django 3.1.2 on 2020-11-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_accounts', '0006_usercommentvote'),
        ('shop_order', '0006_auto_20201109_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop_accounts.useraddress', verbose_name='ارسال به آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(False, 'باطل شده'), (True, 'پرداخت شده')], default=False, verbose_name='پرداخت شده/نشده'),
        ),
    ]
