# Generated by Django 3.1.2 on 2020-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0007_auto_20201109_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=12, verbose_name='کد سفارش'),
        ),
    ]
