# Generated by Django 3.1.2 on 2020-11-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_accounts', '0006_usercommentvote'),
        ('shop_order', '0008_auto_20201109_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_accounts.useraddress', verbose_name='ارسال به آدرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد سفارش'),
        ),
    ]
