# Generated by Django 3.1.2 on 2020-11-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0009_auto_20201109_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
    ]
