# Generated by Django 3.1.2 on 2020-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0010_remove_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(choices=[(True, 'پرداخت شده'), (False, 'پرداخت نشده')], default=False, verbose_name='پرداخت شده/نشده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار کل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار بررسی'), (0, 'سفارش لغو شده'), (2, 'سفارش کامل شده')], default=1, verbose_name='وضعیت سفارش'),
        ),
    ]
