# Generated by Django 3.1.2 on 2020-11-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0011_auto_20201112_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_cost',
            field=models.IntegerField(verbose_name='هزینه کل محصول'),
        ),
    ]
