# Generated by Django 3.1.2 on 2020-11-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_order', '0012_auto_20201112_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه کل محصول'),
        ),
    ]
